const env = process.env
const cnf = Object.freeze({
    API_DOC: env.VUE_APP_API_DOC,
    DOMAIN_HOST_TEMPLATE: env.VUE_APP_DOMAIN_HOST_TEMPLATE,
    API_HOST: env.VUE_APP_API_HOST,
    API_ROOT: env.VUE_APP_API_ROOT,
    API_PUBLIC_ROOT: env.VUE_APP_API_PUBLIC_ROOT,
    PROJECT_NAME: env.VUE_APP_PROJECT_NAME,
    PROJECT_INDEX: env.VUE_APP_PROJECT_INDEX,
    ID_TOKEN_COOKIE_DOMAIN: env.VUE_APP_ID_TOKEN_COOKIE_DOMAIN,
})

export default cnf
